# Generated by Django 5.2 on 2025-04-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedseat',
            name='booking_date',
        ),
    ]
